/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/assets/model/2Geonodes.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/2Geonodes.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={nodes.Plane.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/2Geonodes.glb')
