/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/assets/model/basiclogo2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Basiclogo2(props) {
  const { nodes, materials } = useGLTF("./public/assets/model/basiclogo.glb")
  return (
    <group {...props} dispose={null} scale={1.5}>
      <mesh geometry={nodes.Middle001.geometry} material={materials['Material.003']} position={[0, 0.019, 0]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload("./public/assets/model/basiclogo.glb")
