/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/assets/model/basiclogo3.glb 
*/

import React, { useRef, useEffect, useLayoutEffect } from "react";
import { useGLTF, useAnimations, useScroll } from "@react-three/drei";
import gsap from "gsap";
import { useFrame } from "@react-three/fiber";

export function Basiclogo3(props) {
  const group = useRef();
  const scroll = useScroll();
  const tl = useRef();
  const { nodes, materials,animations } = useGLTF("./public/assets/model/basiclogo3.glb");
  const { actions } = useAnimations(animations, group);
  console.log(actions)
  useFrame((state, delta) => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });
  useLayoutEffect(() => {
    tl.current = gsap.timeline({
      defaults: { duration: 1,  ease: "power1.inOut"},
    });
    tl.current
      // .to(group.current.rotation, { y: -1 }, 2)
      .to(group.current.position, { x: 3 }, 1.5)
      .to(group.current.rotation, { y: 2.5 }, 1.5)

      .to(group.current.position, { x: -3 }, 5)
      .to(group.current.rotation, { y: 0.75}, 5)

      // .to(group.current.rotation, { y: 0 }, 11)
      // .to(group.current.rotation, { x: 1 }, 11)
      .to(group.current.position, { x: 0 }, 11)

      // .to(group.current.rotation, { y: 0 }, 13)
      // .to(group.current.rotation, { x: -1 }, 13)
      .to(group.current.position, { x: 0 }, 13)

      // .to(group.current.rotation, { y: 0 }, 16)
      // .to(group.current.rotation, { x: 0 }, 16)
      .to(group.current.position, { x: 0 }, 16)

      // .to(group.current.rotation, { y: 0 }, 20)
      // .to(group.current.rotation, { x: 0 }, 20)
      .to(group.current.position, { x: 0 }, 20);
  }, []);
  return (
    <group {...props} ref={group} dispose={null} scale={1.75}>
      <mesh
        geometry={nodes.Middle001.geometry}
        material={materials["Material.003"]}
        position={[0, 0.019, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("./public/assets/model/basiclogo3.glb");
