/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/assets/model/basiclogo.glb 
*/

import React, { useRef, useEffect, useLayoutEffect } from "react";
import { useGLTF, useAnimations, useScroll } from "@react-three/drei";
import gsap from "gsap";
import { useFrame } from "@react-three/fiber";

export function Basiclogo(props) {
  const { nodes, materials } = useGLTF("./public/assets/model/basiclogo.glb");
  const group = useRef();

  return (
    <group {...props} dispose={null} scale={1.5}>
      <mesh
        geometry={nodes.Middle001.geometry}
        material={materials["Material.002"]}
        position={[0, 0.019, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("./public/assets/model/basiclogo.glb");
