/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/assets/model/bulk_logo.glb 
*/

import React, { useRef, useEffect, useLayoutEffect } from "react";
import { useGLTF, useAnimations, useScroll } from "@react-three/drei";
import gsap from "gsap";
import { useFrame } from "@react-three/fiber";

export function Bulk_logo(props) {
  const group = useRef();

  const { nodes, materials, animations } = useGLTF(
    "./public/assets/model/bulk_logo.glb"
  );
  const scroll = useScroll();
  const tl = useRef();

  useEffect(() => {
    console.log(scroll.scroll.current);
  }, [scroll.scroll.current]);

  useFrame((state, delta) => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  useLayoutEffect(() => {
    tl.current = gsap.timeline({
      defaults: { duration: 2, ease: "power1.inOut", x: -4 },
    });
    tl.current
      // .to(group.current.rotation, { y: -1 }, 2)
      .to(group.current.position, { x: 1 }, 2)

      // .to(group.current.rotation, { y: 1 }, 6)
      .to(group.current.position, { x: -1 }, 6)

      // .to(group.current.rotation, { y: 0 }, 11)
      // .to(group.current.rotation, { x: 1 }, 11)
      .to(group.current.position, { x: 0 }, 11)

      // .to(group.current.rotation, { y: 0 }, 13)
      // .to(group.current.rotation, { x: -1 }, 13)
      .to(group.current.position, { x: 0 }, 13)

      // .to(group.current.rotation, { y: 0 }, 16)
      // .to(group.current.rotation, { x: 0 }, 16)
      .to(group.current.position, { x: 0 }, 16)

      // .to(group.current.rotation, { y: 0 }, 20)
      // .to(group.current.rotation, { x: 0 }, 20)
      .to(group.current.position, { x: 0 }, 20);
  }, []);

  // const { actions, names } = useAnimations(animations, group);
  // useEffect(() => {
  //   actions[names[0]].reset().fadeIn(0.5).play();
  // }, []);

  return (
    <group {...props} dispose={null} ref={group}>
      <mesh
        geometry={nodes.Middle.geometry}
        material={materials["Material.002"]}
        position={[0, 2.492, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("./public/assets/model/bulk_logo.glb");
