/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/assets/model/logo.glb 
*/

import React, { useRef, useEffect, useLayoutEffect } from "react";
import { useGLTF, useAnimations, useScroll } from "@react-three/drei";
import gsap from "gsap";
import { useFrame } from "@react-three/fiber";

export function Bulk_logo1(props) {
  const group = useRef();
  const scroll = useScroll();
  const tl = useRef();
  const { nodes, materials, animations } = useGLTF(
    "./public/assets/model/bulk_logo1.glb"
  );
  const { actions } = useAnimations(animations, group);
  useFrame((state, delta) => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });
  useLayoutEffect(() => {
    tl.current = gsap.timeline({
      defaults: { duration: 2,  ease: "power1.inOut"},
    });
    tl.current
      // .to(group.current.rotation, { y: -1 }, 2)
      .to(group.current.position, { x: 1 }, 2)

      // .to(group.current.rotation, { y: 1 }, 6)
      .to(group.current.position, { x: -1 }, 6)

      // .to(group.current.rotation, { y: 0 }, 11)
      // .to(group.current.rotation, { x: 1 }, 11)
      .to(group.current.position, { x: 0 }, 11)

      // .to(group.current.rotation, { y: 0 }, 13)
      // .to(group.current.rotation, { x: -1 }, 13)
      .to(group.current.position, { x: 0 }, 13)

      // .to(group.current.rotation, { y: 0 }, 16)
      // .to(group.current.rotation, { x: 0 }, 16)
      .to(group.current.position, { x: 0 }, 16)

      // .to(group.current.rotation, { y: 0 }, 20)
      // .to(group.current.rotation, { x: 0 }, 20)
      .to(group.current.position, { x: 0 }, 20);
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" scale={1.5}>
        <group name="Empty" position={[-2.343, -0.832, 0]} scale={0.97} />
        <group name="Empty001" position={[-2.343, -0.832, 0]} scale={0.97} />
        <group
          name="Area_001"
          position={[0.03, 1.11, 2.129]}
          rotation={[1.251, 0, 0]}
          scale={5.193}
        />
        <group name="Area002" position={[0, 1.115, 0]} scale={5.193} />
        <mesh
          name="Middle001"
          geometry={nodes.Middle001.geometry}
          material={materials["Material.002"]}
          position={[0, 0.019, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Middle_001"
          geometry={nodes.Middle_001.geometry}
          material={nodes.Middle_001.material}
          morphTargetDictionary={nodes.Middle_001.morphTargetDictionary}
          morphTargetInfluences={nodes.Middle_001.morphTargetInfluences}
          position={[0, 0.019, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./public/assets/model/bulk_logo1.glb");
