/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/assets/model/logo2.glb 
*/

import React, { useRef,useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Logo2(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "./public/assets/model/logo2.glb"
  );
  const { actions, names } = useAnimations(animations, group);
  console.log(names);
  useEffect(() => {
    actions[names[0]].reset().fadeIn(0.5).play();
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Turbulence" position={[0, 2.256, 0]} />
        <group name="Wind" position={[0, -0.859, 0]} scale={2.312} />
        <mesh
          name="Middle"
          geometry={nodes.Middle.geometry}
          material={materials.Material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Icosphere"
          geometry={nodes.Icosphere.geometry}
          material={nodes.Icosphere.material}
          position={[8.65, 0, 0]}
          scale={0.24}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./public/assets/model/logo2.glb");
