/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/assets/model/logo.glb 
*/

import React, { useRef, useEffect,forwardRef  } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

// export function Logo(props) {
export const Logo = forwardRef((props, ref) => {
  const group = ref;
  // const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "./public/assets/model/logo.glb"
  );
  const { actions, names } = useAnimations(animations, group);
  useEffect(() => {
    if (actions[names[0]]) {
      actions[names[0]].reset().fadeIn(0.5).play();
    }
  }, [actions, names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty">
          <group
            name="Left_semi"
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 0.25, 1]}
          >
            <mesh
              name="Cylinder002"
              geometry={nodes.Cylinder002.geometry}
              material={materials.Orange_Glass_tex}
            />
            <mesh
              name="Cylinder002_1"
              geometry={nodes.Cylinder002_1.geometry}
              material={materials.Orange_Glass_tex}
            />
          </group>
          <group
            name="Middle"
            rotation={[Math.PI / 2, 0, 0]}
            scale={[1, 0.25, 1]}
          >
            <mesh
              name="Cylinder003"
              geometry={nodes.Cylinder003.geometry}
              material={materials.Orange_Glass_tex}
            />
            <mesh
              name="Cylinder003_1"
              geometry={nodes.Cylinder003_1.geometry}
              material={materials.Orange_Glass_tex}
            />
          </group>
          <group
            name="Right_semi"
            rotation={[Math.PI / 2, 0, 0]}
            scale={[1, 0.25, 1]}
          >
            <mesh
              name="Cylinder"
              geometry={nodes.Cylinder.geometry}
              material={materials.Orange_Glass_tex}
            />
            <mesh
              name="Cylinder_1"
              geometry={nodes.Cylinder_1.geometry}
              material={materials.Orange_Glass_tex}
            />
          </group>
        </group>
      </group>
    </group>
  );
});

useGLTF.preload("./public/assets/model/logo.glb");
