/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/assets/model/logo.glb 
*/

import React, { useRef, useEffect, useLayoutEffect } from "react";
import { useGLTF, useAnimations, useScroll } from "@react-three/drei";
import gsap from "gsap";
import { useFrame } from "@react-three/fiber";

export function Logo4(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "./public/assets/model/logo.glb"
  );
  const { actions } = useAnimations(animations, group);
  console.log(actions);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[-2.343, -0.832, 0]} scale={0.97} />
        <group
          name="Area_001"
          position={[0.03, 1.11, 2.129]}
          rotation={[1.251, 0, 0]}
          scale={5.193}
        />
        <group name="Area" position={[0, 1.115, 0]} scale={5.193} />
        <mesh
          name="Middle_001"
          geometry={nodes.Middle_001.geometry}
          material={nodes.Middle_001.material}
          morphTargetDictionary={nodes.Middle_001.morphTargetDictionary}
          morphTargetInfluences={nodes.Middle_001.morphTargetInfluences}
          position={[0, 0.019, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./public/assets/model/logo.glb");
