/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/assets/model/logo.glb 
*/

import React, { useRef, useEffect, useLayoutEffect } from "react";
import { useGLTF, useAnimations, useScroll } from "@react-three/drei";
import gsap from "gsap";
import { useFrame } from "@react-three/fiber";

export function Logo(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "./public/assets/model/logo.glb"
  );
  const scroll = useScroll();
  const tl = useRef();

  useEffect(() => {
    console.log(scroll.scroll.current);
  }, [scroll.scroll.current]);

  useFrame((state, delta) => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  useLayoutEffect(() => {
    tl.current = gsap.timeline({
      defaults: { duration: 2,  ease: "power1.inOut"},
    });
    tl.current
      // .to(group.current.rotation, { y: -1 }, 2)
      .to(group.current.position, { x: 1 }, 2)

      // .to(group.current.rotation, { y: 1 }, 6)
      .to(group.current.position, { x: -1 }, 6)

      // .to(group.current.rotation, { y: 0 }, 11)
      // .to(group.current.rotation, { x: 1 }, 11)
      .to(group.current.position, { x: 0 }, 11)

      // .to(group.current.rotation, { y: 0 }, 13)
      // .to(group.current.rotation, { x: -1 }, 13)
      .to(group.current.position, { x: 0 }, 13)

      // .to(group.current.rotation, { y: 0 }, 16)
      // .to(group.current.rotation, { x: 0 }, 16)
      .to(group.current.position, { x: 0 }, 16)

      // .to(group.current.rotation, { y: 0 }, 20)
      // .to(group.current.rotation, { x: 0 }, 20)
      .to(group.current.position, { x: 0 }, 20);
  }, []);

  // const { actions, names } = useAnimations(animations, group);
  // useEffect(() => {
  //   actions[names[0]].reset().fadeIn(0.5).play();
  // }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty">
          <group
            name="Left_semi"
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={[1, 0.25, 1]}
          >
            <mesh
              name="Cylinder002"
              geometry={nodes.Cylinder002.geometry}
              material={materials.Orange_Glass_tex}
            />
            <mesh
              name="Cylinder002_1"
              geometry={nodes.Cylinder002_1.geometry}
              material={materials.Orange_Glass_tex}
            />
          </group>
          <group
            name="Middle"
            rotation={[Math.PI / 2, 0, 0]}
            scale={[1, 0.25, 1]}
          >
            <mesh
              name="Cylinder003"
              geometry={nodes.Cylinder003.geometry}
              material={materials.Orange_Glass_tex}
            />
            <mesh
              name="Cylinder003_1"
              geometry={nodes.Cylinder003_1.geometry}
              material={materials.Orange_Glass_tex}
            />
          </group>
          <group
            name="Right_semi"
            rotation={[Math.PI / 2, 0, 0]}
            scale={[1, 0.25, 1]}
          >
            <mesh
              name="Cylinder"
              geometry={nodes.Cylinder.geometry}
              material={materials.Orange_Glass_tex}
            />
            <mesh
              name="Cylinder_1"
              geometry={nodes.Cylinder_1.geometry}
              material={materials.Orange_Glass_tex}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./public/assets/model/logo.glb");
