/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/assets/model/testmodel2.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Testmodel3(props) {
  const { nodes, materials } = useGLTF("./public/assets/model/testmodel3.gltf")
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Particle_sim_logo.geometry} material={nodes.Particle_sim_logo.material} position={[0.093, 1.892, 0]} rotation={[0, 0, 3.106]} scale={[0.019, 0.031, 0.031]} />
      <mesh geometry={nodes.Middle.geometry} material={materials.Material} position={[0, 2.492, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Icosphere.geometry} material={materials.Material} position={[8.65, 0, 0]} scale={0.054} />
    </group>
  )
}

useGLTF.preload("./public/assets/model/testmodel3.gltf")
